### ISSUE TITLE
Example notebooks include local file link

### ISSUE THREAD

**Issue by dschick** [udcm-su/NTMpy#17]
Hi,

some of the notebooks still include some local include, such as:
`sys.path.append("C:/Users/lUKAS/Documents/UDCM/Objects")`

e..g in the Comparisom4.ipynb there is also a non-working import
`import TMM_abs as atmm `

**Comment by luksen99** [comment]
The local file import of the `TMM_abs` module is to pedagogically demonstrate the effect of the Transfer Matrix Method. This module is implemented in the `NTMpy` package but can be separately inspected [here](https://github.com/udcm-su/AbsorptionTMM).
