### ISSUE TITLE
Structure of the python package

### ISSUE THREAD

**Issue by dschick** [udcm-su/NTMpy#18]
what is actually the reason, why the source code is that deep in the package structure?
Usually you would do something like:

`NTMpy/NTMpy/NTMpy.py`

However, you added one extra layer here.

I think, you could also ignore the `build `and `dist `folders in your repo to clean it up a bit.

**Comment by luksen99** [comment]
I followed the [instructions](https://packaging.python.org/tutorials/packaging-projects/) of the Python Packaging User Guide on how to do it. Thank you for the note about the `build` and `dist` folders, but I don´t think it is an actual issue, so I will close it.
